# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/PYNQ-Z1_C.xdc

# Block Designs: bd/Overall_CPU/Overall_CPU.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Overall_CPU || ORIG_REF_NAME==Overall_CPU} -quiet] -quiet

# IP: bd/Overall_CPU/ip/Overall_CPU_datapath_wrapper_0_0/Overall_CPU_datapath_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Overall_CPU_datapath_wrapper_0_0 || ORIG_REF_NAME==Overall_CPU_datapath_wrapper_0_0} -quiet] -quiet

# IP: bd/Overall_CPU/ip/Overall_CPU_processing_system7_0_1/Overall_CPU_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Overall_CPU_processing_system7_0_1 || ORIG_REF_NAME==Overall_CPU_processing_system7_0_1} -quiet] -quiet

# IP: bd/Overall_CPU/ip/Overall_CPU_axi_regmap_0_1/Overall_CPU_axi_regmap_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Overall_CPU_axi_regmap_0_1 || ORIG_REF_NAME==Overall_CPU_axi_regmap_0_1} -quiet] -quiet

# IP: bd/Overall_CPU/ip/Overall_CPU_xbar_1/Overall_CPU_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Overall_CPU_xbar_1 || ORIG_REF_NAME==Overall_CPU_xbar_1} -quiet] -quiet

# IP: bd/Overall_CPU/ip/Overall_CPU_ps7_0_axi_periph_1/Overall_CPU_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Overall_CPU_ps7_0_axi_periph_1 || ORIG_REF_NAME==Overall_CPU_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/Overall_CPU/ip/Overall_CPU_rst_ps7_0_50M_1/Overall_CPU_rst_ps7_0_50M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Overall_CPU_rst_ps7_0_50M_1 || ORIG_REF_NAME==Overall_CPU_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/Overall_CPU/ip/Overall_CPU_blk_mem_gen_0_1/Overall_CPU_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Overall_CPU_blk_mem_gen_0_1 || ORIG_REF_NAME==Overall_CPU_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/Overall_CPU/ip/Overall_CPU_xlconstant_0_1/Overall_CPU_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Overall_CPU_xlconstant_0_1 || ORIG_REF_NAME==Overall_CPU_xlconstant_0_1} -quiet] -quiet

# IP: bd/Overall_CPU/ip/Overall_CPU_xlconcat_0_1/Overall_CPU_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Overall_CPU_xlconcat_0_1 || ORIG_REF_NAME==Overall_CPU_xlconcat_0_1} -quiet] -quiet

# IP: bd/Overall_CPU/ip/Overall_CPU_axi_bram_ctrl_0_0/Overall_CPU_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Overall_CPU_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Overall_CPU_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Overall_CPU/ip/Overall_CPU_auto_pc_0/Overall_CPU_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Overall_CPU_auto_pc_0 || ORIG_REF_NAME==Overall_CPU_auto_pc_0} -quiet] -quiet

# XDC: bd/Overall_CPU/Overall_CPU_ooc.xdc
