#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : Overall_CPU.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Nov 07 15:38:27 -0500 2023
# SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: Overall_CPU.sh [-help]
# usage: Overall_CPU.sh [-lib_map_path]
# usage: Overall_CPU.sh [-noclean_files]
# usage: Overall_CPU.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'Overall_CPU.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xlslice_v1_0_1 xil_defaultlib)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "Overall_CPU.sh - Script generated by export_simulation (Vivado v2018.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xlslice_v1_0_1 $vlogan_opts +v2k \
    "$ref_dir/../../../../Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ipshared/f3db/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_xlslice_0_0/sim/datapath_xlslice_0_0.v" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_xlslice_1_0/sim/datapath_xlslice_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_Control_Unit_8_0_0/sim/datapath_Control_Unit_8_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_PC_8_0_0/sim/datapath_PC_8_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_two2one_mux_8_0_0/sim/datapath_two2one_mux_8_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_Memory_Data_Register_0_0/sim/datapath_Memory_Data_Register_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_Instruction_Register_0_0/sim/datapath_Instruction_Register_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_register_file_8_0_0/sim/datapath_register_file_8_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_fivebit_2to1_mux_8_0_0/sim/datapath_fivebit_2to1_mux_8_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_Sign_Extend_8_0_0/sim/datapath_Sign_Extend_8_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_Shift_Left_2_8_0_0/sim/datapath_Shift_Left_2_8_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_Shift_Left_2_28_8_0_0/sim/datapath_Shift_Left_2_28_8_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_Reg_A_8_0_0/sim/datapath_Reg_A_8_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_Reg_B_8_0_0/sim/datapath_Reg_B_8_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_two2one_mux_8_2_0/sim/datapath_two2one_mux_8_2_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_four2two_mux_8_0_0/sim/datapath_four2two_mux_8_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_ALU_0_0/sim/datapath_ALU_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_ALUOut_8_0_0/sim/datapath_ALUOut_8_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_four2three_mux_8_0_0/sim/datapath_four2three_mux_8_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_andGateorGate_0_0/sim/datapath_andGateorGate_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_fivebit_2to1_mux_8_1_0/sim/datapath_fivebit_2to1_mux_8_1_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_Two2one_1bit_mux_0_0/sim/datapath_Two2one_1bit_mux_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_count_leading_ones_0_0/sim/datapath_count_leading_ones_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_two2one_mux_8_3_0/sim/datapath_two2one_mux_8_3_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_loading_mux_0_0/sim/datapath_loading_mux_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_Multiplier_32_bit_0_0/sim/datapath_Multiplier_32_bit_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_HILO_reg_0_0/sim/datapath_HILO_reg_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_HILO_reg_1_0/sim/datapath_HILO_reg_1_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/Control_Unit_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/PC_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/two2one_mux_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/Memory_Data_Register_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/Instruction_Register_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/register_file_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/fivebit_2to1_mux_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/Sign_Extend_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/Shift_Left_2_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/Shift_Left_2_28_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/Reg_A_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/Reg_B_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/four2two_mux_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/imports/src/Arith_Unit.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/imports/new/Logical.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/imports/new/comparator_unit.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/imports/new/shifter_unit.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/imports/new/ALU.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/ALUOut_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/four2three_mux_8.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/andGate.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/sim/datapath.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/Two2one_1bit_mux.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/count_leading_ones.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/loading_mux.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_3/Lab_3.srcs/sources_1/new/adder64bit.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_3/Lab_3.srcs/sources_1/new/control_unit.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_3/Lab_3.srcs/sources_1/new/counter5bit.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_3/Lab_3.srcs/sources_1/new/flipflop64bit.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_3/Lab_3.srcs/sources_1/new/shift32bit.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_3/Lab_3.srcs/sources_1/new/shift64bit.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_3/Lab_3.srcs/sources_1/new/Multiplier_32_bit.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/HILO_reg.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/hdl/datapath_wrapper.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/ipshared/14fb/Mac/Home/Downloads/CPU_memory.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/new/dummyMemory.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/ip/Overall_CPU_datapath_wrapper_0_0/sim/Overall_CPU_datapath_wrapper_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/ip/Overall_CPU_CPU_memory_0_0/sim/Overall_CPU_CPU_memory_0_0.vhd" \
    "$ref_dir/../../../bd/Overall_CPU/sim/Overall_CPU.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.Overall_CPU xil_defaultlib.glbl -o Overall_CPU_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./Overall_CPU_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./Overall_CPU.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key Overall_CPU_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc Overall_CPU_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./Overall_CPU.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: Overall_CPU.sh [-help]\n\
Usage: Overall_CPU.sh [-lib_map_path]\n\
Usage: Overall_CPU.sh [-reset_run]\n\
Usage: Overall_CPU.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
