webtalk_init -webtalk_dir C:/Users/travisallabon/Lab_1_Design_Adder/Lab_1_Design_Adder.sim/sim_1/behav/xsim/xsim.dir/AdderSubtractor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Sep 18 20:23:44 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211142296_1777514147_210729583_846" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a0bb617a-baf5-49a0-895f-cac693409f32" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7fcc4f13244e4f8d81f9ef20e60ae745" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Apple Silicon" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3200 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15328_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4293539048 -regid "211142296_1777514147_210729583_846" -xml C:/Users/travisallabon/Lab_1_Design_Adder/Lab_1_Design_Adder.sim/sim_1/behav/xsim/xsim.dir/AdderSubtractor_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/travisallabon/Lab_1_Design_Adder/Lab_1_Design_Adder.sim/sim_1/behav/xsim/xsim.dir/AdderSubtractor_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/travisallabon/Lab_1_Design_Adder/Lab_1_Design_Adder.sim/sim_1/behav/xsim/xsim.dir/AdderSubtractor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
