# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/ip/Overall_CPU_processing_system7_0_1/Overall_CPU_processing_system7_0_1.xci
# IP: The module: 'Overall_CPU_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/ip/Overall_CPU_processing_system7_0_1/Overall_CPU_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Overall_CPU_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/ip/Overall_CPU_processing_system7_0_1/Overall_CPU_processing_system7_0_1.xci
# IP: The module: 'Overall_CPU_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/ip/Overall_CPU_processing_system7_0_1/Overall_CPU_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Overall_CPU_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
