# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/ip/Overall_CPU_datapath_wrapper_0_0/Overall_CPU_datapath_wrapper_0_0.xci
# IP: The module: 'Overall_CPU_datapath_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_xlslice_0_0/datapath_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_xlslice_0_0 || ORIG_REF_NAME==datapath_xlslice_0_0} -quiet] -quiet

# IP: c:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_xlslice_1_0/datapath_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_xlslice_1_0 || ORIG_REF_NAME==datapath_xlslice_1_0} -quiet] -quiet

# XDC: c:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/constrs_1/imports/Downloads/PYNQ-Z1_C.xdc
# XDC: The top module name and the constraint reference have the same name: 'Overall_CPU_datapath_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/datapath_ooc.xdc

# IP: C:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/ip/Overall_CPU_datapath_wrapper_0_0/Overall_CPU_datapath_wrapper_0_0.xci
# IP: The module: 'Overall_CPU_datapath_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_xlslice_0_0/datapath_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_xlslice_0_0 || ORIG_REF_NAME==datapath_xlslice_0_0} -quiet] -quiet

# IP: c:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/ip/datapath_xlslice_1_0/datapath_xlslice_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_xlslice_1_0 || ORIG_REF_NAME==datapath_xlslice_1_0} -quiet] -quiet

# XDC: c:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/constrs_1/imports/Downloads/PYNQ-Z1_C.xdc
# XDC: The top module name and the constraint reference have the same name: 'Overall_CPU_datapath_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/Overall_CPU/Users/travisallabon/Lab_4_Inshallah/Lab_4_Inshallah.srcs/sources_1/bd/datapath/datapath_ooc.xdc
