# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ECE-1195/PYNQ-Z1_C.xdc

# Block Designs: bd/Lab_2_Block_Design/Lab_2_Block_Design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_Block_Design || ORIG_REF_NAME==Lab_2_Block_Design} -quiet] -quiet

# IP: bd/Lab_2_Block_Design/ip/Lab_2_Block_Design_axi_regmap_0_0/Lab_2_Block_Design_axi_regmap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_Block_Design_axi_regmap_0_0 || ORIG_REF_NAME==Lab_2_Block_Design_axi_regmap_0_0} -quiet] -quiet

# IP: bd/Lab_2_Block_Design/ip/Lab_2_Block_Design_ALU_0_0/Lab_2_Block_Design_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_Block_Design_ALU_0_0 || ORIG_REF_NAME==Lab_2_Block_Design_ALU_0_0} -quiet] -quiet

# IP: bd/Lab_2_Block_Design/ip/Lab_2_Block_Design_processing_system7_0_0/Lab_2_Block_Design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_Block_Design_processing_system7_0_0 || ORIG_REF_NAME==Lab_2_Block_Design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab_2_Block_Design/ip/Lab_2_Block_Design_auto_pc_0/Lab_2_Block_Design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_Block_Design_auto_pc_0 || ORIG_REF_NAME==Lab_2_Block_Design_auto_pc_0} -quiet] -quiet

# IP: bd/Lab_2_Block_Design/ip/Lab_2_Block_Design_ps7_0_axi_periph_0/Lab_2_Block_Design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_Block_Design_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab_2_Block_Design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab_2_Block_Design/ip/Lab_2_Block_Design_rst_ps7_0_100M_0/Lab_2_Block_Design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_Block_Design_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab_2_Block_Design_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/Lab_2_Block_Design/Lab_2_Block_Design_ooc.xdc
